# Generated by Django 5.0 on 2023-12-22 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profiles_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
    ]
